#Imports

In [ ]:
#Sickit learn met régulièrement à jour des versions et
#indique des futurs warnings.
#ces deux lignes permettent de ne pas les afficher.
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)
# librairies générales
import pandas as pd
import re
from tabulate import tabulate
import time
import numpy as np
import pickle
import string
import base64
import sys
# librairie affichage
import matplotlib.pyplot as plt
import seaborn as sns
# librairies scikit learn
import sklearn
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.base import TransformerMixin
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score
# librairies des classifiers utilisés
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
import warnings
warnings.filterwarnings("ignore")

In [ ]:
# pour monter son drive Google Drive local
from google.colab import drive
drive.mount('/content/gdrive')
my_local_drive='/content/gdrive/My Drive/Colab Notebooks/TER'
# Ajout du path pour les librairies, fonctions et données
sys.path.append(my_local_drive)
# Se positionner sur le répertoire associé
%cd $my_local_drive
%pwd

Mounted at /content/gdrive
/content/gdrive/My Drive/Colab Notebooks/TER


'/content/gdrive/My Drive/Colab Notebooks/TER'

#Classification

In [ ]:
import pandas as pd
V2 = pd.read_excel("ISAC_V2.xlsx")
V2.head()

Unnamed: 0  Chip_Code Chip_Type  French_Residence_Department  French_Region  \
0    WQW0008  202272574   ISAC_V2                           51              6   
1    WQW0054  210553086   ISAC_V2                           51              6   
2    WQW0059  210993011   ISAC_V2                           51              6   
3    WQW0160  221402048   ISAC_V2                           51              6   
4    WQW0189  223042355   ISAC_V2                           67              6   

   Rural_or_urban_area  Allergy_Present  Severe_Allergy  Respiratory_Allergy  \
0                    1                0               0                    0   
1                    1                0               0                    0   
2                    1                0               0                    0   
3                    1                0               0                    0   
4                    0                0               0                    0   

   Food_Allergy  ...  Min_Animaux  Moyenne_Alimentaires  Max_Alimentaires  \
0             0  ...            0               0.00000              0.00   
1             0  ...            0               2.38800             19.25   
2             0  ...            0               0.00000              0.00   
3             0  ...           -1               0.12850              1.91   
4             0  ...            0               0.04025              0.54   

   Min_Alimentaires  Moyenne_Glycanes  Max_Glycanes  Min_Glycanes  \
0                 0               0.0           0.0             0   
1                 0               0.0           0.0             0   
2                 0               0.0           0.0             0   
3                -1               0.0           0.0             0   
4                 0               0.0           0.0             0   

   Moyenne_Autres  Max_Autres  Min_Autres  
0             0.0         0.0         0.0  
1             0.0         0.0         0.0  
2             0.0         0.0         0.0  
3             0.0         0.0         0.0  
4             0.0         0.0         0.0  

[5 rows x 127 columns]

In [ ]:
target_1 = [
    "Allergy_Present",
    "Respiratory_Allergy",
    "Food_Allergy",
    "Venom_Allergy",
    "Severe_Allergy",
    "Type_of_Food_Allergy_Other",
    "Type_of_Respiratory_Allergy_IGE_Pollen_Herb",
    "Type_of_Respiratory_Allergy_IGE_Pollen_Tree",
    "Type_of_Respiratory_Allergy_IGE_Dander_Animals",
    "Type_of_Respiratory_Allergy_IGE_Mite_Cockroach",
    "Type_of_Respiratory_Allergy_IGE_Molds_Yeast",
    "Type_of_Respiratory_Allergy_ARIA",
    "Type_of_Respiratory_Allergy_CONJ",
    "Type_of_Respiratory_Allergy_IGE_Pollen_Gram",
    "Type_of_Respiratory_Allergy_GINA",
    "Type_of_Food_Allergy_Aromatics",
    "Type_of_Food_Allergy_Cereals_&_Seeds",
    "Type_of_Food_Allergy_Egg",
    "Type_of_Food_Allergy_Fish",
    "Type_of_Food_Allergy_Fruits_and_Vegetables",
    "Type_of_Food_Allergy_Mammalian_Milk",
    "Type_of_Food_Allergy_Oral_Syndrom",
    "Type_of_Food_Allergy_Other_Legumes",
    "Type_of_Food_Allergy_Peanut",
    "Type_of_Food_Allergy_Shellfish",
    "Type_of_Food_Allergy_TPO",
    "Type_of_Food_Allergy_Tree_Nuts",
    "Type_of_Venom_Allergy_ATCD_Venom",
    "Type_of_Venom_Allergy_IGE_Venom",
]

extra_columns = [
    "Chip_Type",
    "Chip_Code",
    "French_Region",
    "French_Residence_Department"
    ]

extra = ['History_of_food_anaphylaxis','First_degree_family_history_of_atopy', 'History_of_atopic_dematitis', 'History_of_mast_cell_disorders',
         'History_of_hymenoptera_venom_anaphylaxis','Mammalian_meat']
extra_1 = ["Conjunctivitis", "Oral_Syndrom", "Cardiovascular_symptoms", "Respiratory_symptoms", "Gastrointestinal_symptoms", "Food_polyallergies"]

Gina = ["GINA_(asthma)_0", "GINA_(asthma)_1", "GINA_(asthma)_2", "GINA_(asthma)_3", "GINA_(asthma)_4", "GINA_(asthma)_5", "GINA_(asthma)_9"]
inconnu = ["Treatment_of_athsma_9", "Treatment_of_rhinitis_9", "General_cofactors_9",
           "Age_of_onsets_9", "ARIA_(rhinitis)_9", "GINA_(asthma)_9", "Treatment_of_atopic_dematitis_9"]
Aria = ["ARIA_(rhinitis)_9", "ARIA_(rhinitis)_0", "ARIA_(rhinitis)_1", "ARIA_(rhinitis)_2", "ARIA_(rhinitis)_3", "ARIA_(rhinitis)_4", "ARIA_(rhinitis)_5"]

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.metrics import (
    f1_score, accuracy_score, recall_score,
    precision_score, confusion_matrix, roc_auc_score, roc_curve
)
from imblearn.over_sampling import SMOTE
import plotly.graph_objects as go

targets = ["Allergy_Present", "Respiratory_Allergy", "Food_Allergy"]

models = {
    "RandomForest": RandomForestClassifier(random_state=42),
    "XGBoost": XGBClassifier(random_state=42, eval_metric="logloss", use_label_encoder=False),
    "LogisticRegression": LogisticRegression(max_iter=1000, random_state=42),
    "SVM": SVC(probability=True, random_state=42)
}

X = V2.copy()
X.drop(target_1, axis=1, inplace=True)
X.drop(extra_columns, axis=1, inplace=True)
X.drop(extra, axis=1, inplace=True)
X.drop(inconnu, axis=1, inplace=True)
X = X.iloc[:, 1:]

results = []
kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

for target in targets:
    y = V2[target]

    for model_name, base_model in models.items():
        f1_class0_scores, f1_class1_scores = [], []
        precision_scores, acc_scores, recall_scores, auc_scores = [], [], [], []

        for train_idx, test_idx in kfold.split(X, y):
            X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
            y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

            smote = SMOTE(random_state=42)
            X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

            base_model.fit(X_train_res, y_train_res)
            y_pred = base_model.predict(X_test)

            acc_scores.append(accuracy_score(y_test, y_pred))
            recall_scores.append(recall_score(y_test, y_pred, zero_division=0))
            precision_scores.append(precision_score(y_test, y_pred, average='weighted', zero_division=0))
            f1_class0_scores.append(f1_score(y_test, y_pred, pos_label=0, zero_division=0))
            f1_class1_scores.append(f1_score(y_test, y_pred, pos_label=1, zero_division=0))

            if hasattr(base_model, "predict_proba"):
                y_proba = base_model.predict_proba(X_test)[:, 1]
                auc_scores.append(roc_auc_score(y_test, y_proba))

        base_model.fit(X, y)
        y_pred_full = base_model.predict(X)
        y_proba_full = base_model.predict_proba(X)[:, 1] if hasattr(base_model, "predict_proba") else None
        matrix = confusion_matrix(y, y_pred_full)

        print(f"\n🔍 Target: {target} | Model: {model_name}")
        print(f"📈 Accuracy: {np.mean(acc_scores):.4f}")
        print(f"🎯 F1 (0): {np.mean(f1_class0_scores):.4f} | F1 (1): {np.mean(f1_class1_scores):.4f}")
        print(f"📊 Precision: {np.mean(precision_scores):.4f} | AUC: {np.mean(auc_scores) if auc_scores else 'N/A'}")
        print("📊 Confusion Matrix:\n", matrix)

        if y_proba_full is not None:
            fpr, tpr, _ = roc_curve(y, y_proba_full)
            fig = go.Figure()
            fig.add_trace(go.Scatter(x=fpr, y=tpr, mode='lines', name=f"{model_name} (AUC={np.mean(auc_scores):.2f})"))
            fig.add_trace(go.Scatter(x=[0, 1], y=[0, 1], mode='lines', name='Random', line=dict(dash='dash')))
            fig.update_layout(
                title=f"ROC Curve - {target} - {model_name}",
                xaxis_title="False Positive Rate",
                yaxis_title="True Positive Rate",
                width=700, height=500
            )
            fig.show()

        results.append({
            "Target": target,
            "Model": model_name,
            "F1_Class_0": np.mean(f1_class0_scores),
            "F1_Class_1": np.mean(f1_class1_scores),
            "Precision": np.mean(precision_scores),
            "Accuracy": np.mean(acc_scores),
            "Recall": np.mean(recall_scores),
            "AUC_ROC": np.mean(auc_scores) if auc_scores else np.nan
        })

pd.DataFrame(results).to_csv("results_V2_Allergie.csv", index=False)


🔍 Target: Allergy_Present | Model: RandomForest
📈 Accuracy: 0.9898
🎯 F1 (0): 0.9845 | F1 (1): 0.9923
📊 Precision: 0.9900 | AUC: 0.9986316568047338
📊 Confusion Matrix:
 [[258   0]
 [  1 522]]



🔍 Target: Allergy_Present | Model: XGBoost
📈 Accuracy: 0.9872
🎯 F1 (0): 0.9807 | F1 (1): 0.9904
📊 Precision: 0.9876 | AUC: 0.9996671597633136
📊 Confusion Matrix:
 [[258   0]
 [  1 522]]



🔍 Target: Allergy_Present | Model: LogisticRegression
📈 Accuracy: 0.9744
🎯 F1 (0): 0.9622 | F1 (1): 0.9807
📊 Precision: 0.9756 | AUC: 0.9956044713631795
📊 Confusion Matrix:
 [[241  17]
 [  5 518]]



🔍 Target: Allergy_Present | Model: SVM
📈 Accuracy: 0.9488
🎯 F1 (0): 0.9189 | F1 (1): 0.9626
📊 Precision: 0.9500 | AUC: 0.9649851791894608
📊 Confusion Matrix:
 [[232  26]
 [  7 516]]



🔍 Target: Respiratory_Allergy | Model: RandomForest
📈 Accuracy: 0.9859
🎯 F1 (0): 0.9811 | F1 (1): 0.9887
📊 Precision: 0.9864 | AUC: 0.9992610837438424
📊 Confusion Matrix:
 [[297   0]
 [  0 484]]



🔍 Target: Respiratory_Allergy | Model: XGBoost
📈 Accuracy: 0.9859
🎯 F1 (0): 0.9815 | F1 (1): 0.9886
📊 Precision: 0.9862 | AUC: 0.9980332707795763
📊 Confusion Matrix:
 [[297   0]
 [  0 484]]



🔍 Target: Respiratory_Allergy | Model: LogisticRegression
📈 Accuracy: 0.9423
🎯 F1 (0): 0.9237 | F1 (1): 0.9536
📊 Precision: 0.9435 | AUC: 0.989647988505747
📊 Confusion Matrix:
 [[282  15]
 [  5 479]]



🔍 Target: Respiratory_Allergy | Model: SVM
📈 Accuracy: 0.9039
🎯 F1 (0): 0.8582 | F1 (1): 0.9272
📊 Precision: 0.9132 | AUC: 0.9480409433888498
📊 Confusion Matrix:
 [[235  62]
 [  7 477]]



🔍 Target: Food_Allergy | Model: RandomForest
📈 Accuracy: 0.9552
🎯 F1 (0): 0.9604 | F1 (1): 0.9482
📊 Precision: 0.9577 | AUC: 0.9904201434636217
📊 Confusion Matrix:
 [[451   0]
 [  0 330]]



🔍 Target: Food_Allergy | Model: XGBoost
📈 Accuracy: 0.9475
🎯 F1 (0): 0.9544 | F1 (1): 0.9381
📊 Precision: 0.9483 | AUC: 0.9859361733274777
📊 Confusion Matrix:
 [[451   0]
 [  0 330]]



🔍 Target: Food_Allergy | Model: LogisticRegression
📈 Accuracy: 0.9027
🎯 F1 (0): 0.9133 | F1 (1): 0.8886
📊 Precision: 0.9069 | AUC: 0.9524681598594642
📊 Confusion Matrix:
 [[423  28]
 [ 23 307]]



🔍 Target: Food_Allergy | Model: SVM
📈 Accuracy: 0.8565
🎯 F1 (0): 0.8801 | F1 (1): 0.8206
📊 Precision: 0.8612 | AUC: 0.9368979651588347
📊 Confusion Matrix:
 [[426  25]
 [ 84 246]]


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.metrics import (
    f1_score, accuracy_score, recall_score,
    precision_score, confusion_matrix, roc_auc_score, roc_curve
)
from imblearn.over_sampling import SMOTE
import plotly.graph_objects as go

V2_sev = V2[V2["Allergy_Present"] == 1]
targets = ["Severe_Allergy"]
models = {
    "RandomForest": RandomForestClassifier(random_state=42),
    "XGBoost": XGBClassifier(random_state=42, eval_metric="logloss", use_label_encoder=False),
    "LogisticRegression": LogisticRegression(max_iter=1000, random_state=42),
    "SVM": SVC(probability=True, random_state=42)
}
X = V2_sev.copy()
X.drop(target_1, axis=1, inplace=True)
X.drop(extra_columns, axis=1, inplace=True)
X.drop(extra, axis=1, inplace=True)
X.drop(inconnu, axis=1, inplace=True)
X = X.iloc[:, 1:]
results_severe = []
kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

for target in targets:
    y = V2_sev[target]

    for model_name, base_model in models.items():
        f1_class0_scores, f1_class1_scores = [], []
        precision_scores, acc_scores, recall_scores, auc_scores = [], [], [], []

        for train_idx, test_idx in kfold.split(X, y):
            X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
            y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

            smote = SMOTE(random_state=42)
            X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

            base_model.fit(X_train_res, y_train_res)
            y_pred = base_model.predict(X_test)

            acc_scores.append(accuracy_score(y_test, y_pred))
            recall_scores.append(recall_score(y_test, y_pred, zero_division=0))
            precision_scores.append(precision_score(y_test, y_pred, average='weighted', zero_division=0))
            f1_class0_scores.append(f1_score(y_test, y_pred, pos_label=0, zero_division=0))
            f1_class1_scores.append(f1_score(y_test, y_pred, pos_label=1, zero_division=0))

            if hasattr(base_model, "predict_proba"):
                y_proba = base_model.predict_proba(X_test)[:, 1]
                auc_scores.append(roc_auc_score(y_test, y_proba))

        base_model.fit(X, y)
        y_pred_full = base_model.predict(X)
        y_proba_full = base_model.predict_proba(X)[:, 1] if hasattr(base_model, "predict_proba") else None
        matrix = confusion_matrix(y, y_pred_full)

        print(f"\n🔍 Target: {target} | Model: {model_name}")
        print(f"📈 Accuracy: {np.mean(acc_scores):.4f}")
        print(f"🎯 F1 (0): {np.mean(f1_class0_scores):.4f} | F1 (1): {np.mean(f1_class1_scores):.4f}")
        print(f"📊 Precision: {np.mean(precision_scores):.4f} | AUC: {np.mean(auc_scores) if auc_scores else 'N/A'}")
        print("📊 Confusion Matrix:\n", matrix)

        if y_proba_full is not None:
            fpr, tpr, _ = roc_curve(y, y_proba_full)
            fig = go.Figure()
            fig.add_trace(go.Scatter(x=fpr, y=tpr, mode='lines', name=f"{model_name} (AUC={np.mean(auc_scores):.2f})"))
            fig.add_trace(go.Scatter(x=[0, 1], y=[0, 1], mode='lines', name='Random', line=dict(dash='dash')))
            fig.update_layout(
                title=f"ROC Curve - {target} - {model_name}",
                xaxis_title="False Positive Rate",
                yaxis_title="True Positive Rate",
                width=700, height=500
            )
            fig.show()

        results_severe.append({
            "Target": target,
            "Model": model_name,
            "F1_Class_0": np.mean(f1_class0_scores),
            "F1_Class_1": np.mean(f1_class1_scores),
            "Precision": np.mean(precision_scores),
            "Accuracy": np.mean(acc_scores),
            "Recall": np.mean(recall_scores),
            "AUC_ROC": np.mean(auc_scores) if auc_scores else np.nan
        })

pd.DataFrame(results_severe).to_csv("results_V2_severe.csv", index=False)


🔍 Target: Severe_Allergy | Model: RandomForest
📈 Accuracy: 0.9542
🎯 F1 (0): 0.8945 | F1 (1): 0.9707
📊 Precision: 0.9558 | AUC: 0.9838068181818184
📊 Confusion Matrix:
 [[118   0]
 [  0 405]]



🔍 Target: Severe_Allergy | Model: XGBoost
📈 Accuracy: 0.9446
🎯 F1 (0): 0.8762 | F1 (1): 0.9643
📊 Precision: 0.9460 | AUC: 0.9835449002217296
📊 Confusion Matrix:
 [[118   0]
 [  0 405]]



🔍 Target: Severe_Allergy | Model: LogisticRegression
📈 Accuracy: 0.9065
🎯 F1 (0): 0.7969 | F1 (1): 0.9390
📊 Precision: 0.9109 | AUC: 0.957055155210643
📊 Confusion Matrix:
 [[105  13]
 [  9 396]]



🔍 Target: Severe_Allergy | Model: SVM
📈 Accuracy: 0.6331
🎯 F1 (0): 0.5071 | F1 (1): 0.7064
📊 Precision: 0.8003 | AUC: 0.7994466001478197
📊 Confusion Matrix:
 [[  0 118]
 [  0 405]]


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.metrics import (
    f1_score, accuracy_score, recall_score,
    precision_score, confusion_matrix, roc_auc_score, roc_curve
)
from imblearn.over_sampling import SMOTE
import plotly.graph_objects as go

# Données respiratoires
V2_res = V2[V2["Respiratory_Allergy"] == 1]

targets = ["Type_of_Respiratory_Allergy_IGE_Pollen_Herb",
    "Type_of_Respiratory_Allergy_IGE_Pollen_Tree",
    "Type_of_Respiratory_Allergy_IGE_Dander_Animals",
    "Type_of_Respiratory_Allergy_IGE_Mite_Cockroach",
    "Type_of_Respiratory_Allergy_IGE_Molds_Yeast",
    "Type_of_Respiratory_Allergy_ARIA",
    "Type_of_Respiratory_Allergy_CONJ",
    "Type_of_Respiratory_Allergy_IGE_Pollen_Gram",
    "Type_of_Respiratory_Allergy_GINA"]

models = {
    "RandomForest": RandomForestClassifier(random_state=42),
    "XGBoost": XGBClassifier(random_state=42, eval_metric="logloss", use_label_encoder=False),
    "LogisticRegression": LogisticRegression(max_iter=1000, random_state=42),
    "SVM": SVC(probability=True, random_state=42)
}

X = V2_res.copy()
X.drop(target_1, axis=1, inplace=True)
X.drop(extra_columns, axis=1, inplace=True)
X.drop(extra, axis=1, inplace=True)
X.drop(inconnu, axis=1, inplace=True)
X = X.iloc[:, 1:]

results_res = []
kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

# Boucle principale
for target in targets:
    y = V2_res[target]

    for model_name, base_model in models.items():
        f1_class0_scores, f1_class1_scores = [], []
        precision_scores, acc_scores, recall_scores, auc_scores = [], [], [], []

        print(f"\n🔍 Target: {target} | Model: {model_name}")

        for train_idx, test_idx in kfold.split(X, y):
            X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
            y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

            # Application de SMOTE sur les données d'entraînement
            smote = SMOTE(random_state=42)
            X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

            base_model.fit(X_train_res, y_train_res)
            y_pred = base_model.predict(X_test)

            acc_scores.append(accuracy_score(y_test, y_pred))
            recall_scores.append(recall_score(y_test, y_pred, zero_division=0))
            precision_scores.append(precision_score(y_test, y_pred, average='weighted', zero_division=0))
            f1_class0_scores.append(f1_score(y_test, y_pred, pos_label=0, zero_division=0))
            f1_class1_scores.append(f1_score(y_test, y_pred, pos_label=1, zero_division=0))

            if hasattr(base_model, "predict_proba"):
                y_proba = base_model.predict_proba(X_test)[:, 1]
                auc_scores.append(roc_auc_score(y_test, y_proba))

        # Entraînement final sur tout X (sans SMOTE ici, car prédiction globale)
        base_model.fit(X, y)
        y_pred_full = base_model.predict(X)
        y_proba_full = base_model.predict_proba(X)[:, 1] if hasattr(base_model, "predict_proba") else None
        matrix = confusion_matrix(y, y_pred_full)

        print(f"📈 Accuracy: {np.mean(acc_scores):.4f}")
        print(f"🎯 F1 (0): {np.mean(f1_class0_scores):.4f} | F1 (1): {np.mean(f1_class1_scores):.4f}")
        print(f"📊 Precision: {np.mean(precision_scores):.4f} | AUC: {np.mean(auc_scores) if auc_scores else 'N/A'}")
        print("📊 Confusion Matrix:\n", matrix)

        if y_proba_full is not None:
            fpr, tpr, _ = roc_curve(y, y_proba_full)
            fig = go.Figure()
            fig.add_trace(go.Scatter(x=fpr, y=tpr, mode='lines', name=f"{model_name} (AUC={np.mean(auc_scores):.2f})"))
            fig.add_trace(go.Scatter(x=[0, 1], y=[0, 1], mode='lines', name='Random', line=dict(dash='dash')))
            fig.update_layout(
                title=f"ROC Curve - {target} - {model_name}",
                xaxis_title="False Positive Rate",
                yaxis_title="True Positive Rate",
                width=700, height=500
            )
            fig.show()

        results_res.append({
            "Target": target,
            "Model": model_name,
            "F1_Class_0": np.mean(f1_class0_scores),
            "F1_Class_1": np.mean(f1_class1_scores),
            "Precision": np.mean(precision_scores),
            "Accuracy": np.mean(acc_scores),
            "Recall": np.mean(recall_scores),
            "AUC_ROC": np.mean(auc_scores) if auc_scores else np.nan
        })

pd.DataFrame(results_res).to_csv("results_V2_respiratoire.csv", index=False)


🔍 Target: Type_of_Respiratory_Allergy_IGE_Pollen_Herb | Model: RandomForest
📈 Accuracy: 0.7914
🎯 F1 (0): 0.8483 | F1 (1): 0.6639
📊 Precision: 0.7902 | AUC: 0.8670862926136362
📊 Confusion Matrix:
 [[328   0]
 [  0 156]]



🔍 Target: Type_of_Respiratory_Allergy_IGE_Pollen_Herb | Model: XGBoost
📈 Accuracy: 0.8016
🎯 F1 (0): 0.8535 | F1 (1): 0.6903
📊 Precision: 0.8052 | AUC: 0.8659189551767676
📊 Confusion Matrix:
 [[328   0]
 [  0 156]]



🔍 Target: Type_of_Respiratory_Allergy_IGE_Pollen_Herb | Model: LogisticRegression
📈 Accuracy: 0.8017
🎯 F1 (0): 0.8592 | F1 (1): 0.6594
📊 Precision: 0.8015 | AUC: 0.825619476010101
📊 Confusion Matrix:
 [[318  10]
 [ 59  97]]



🔍 Target: Type_of_Respiratory_Allergy_IGE_Pollen_Herb | Model: SVM
📈 Accuracy: 0.7461
🎯 F1 (0): 0.8031 | F1 (1): 0.6305
📊 Precision: 0.7645 | AUC: 0.8063107638888889
📊 Confusion Matrix:
 [[315  13]
 [100  56]]



🔍 Target: Type_of_Respiratory_Allergy_IGE_Pollen_Tree | Model: RandomForest
📈 Accuracy: 0.9050
🎯 F1 (0): 0.8931 | F1 (1): 0.9139
📊 Precision: 0.9121 | AUC: 0.963965663965664
📊 Confusion Matrix:
 [[215   0]
 [  0 269]]



🔍 Target: Type_of_Respiratory_Allergy_IGE_Pollen_Tree | Model: XGBoost
📈 Accuracy: 0.8823
🎯 F1 (0): 0.8677 | F1 (1): 0.8937
📊 Precision: 0.8855 | AUC: 0.9508204758204759
📊 Confusion Matrix:
 [[215   0]
 [  0 269]]



🔍 Target: Type_of_Respiratory_Allergy_IGE_Pollen_Tree | Model: LogisticRegression
📈 Accuracy: 0.8429
🎯 F1 (0): 0.8336 | F1 (1): 0.8507
📊 Precision: 0.8508 | AUC: 0.9233911150577818
📊 Confusion Matrix:
 [[194  21]
 [ 29 240]]



🔍 Target: Type_of_Respiratory_Allergy_IGE_Pollen_Tree | Model: SVM
📈 Accuracy: 0.8181
🎯 F1 (0): 0.8137 | F1 (1): 0.8210
📊 Precision: 0.8339 | AUC: 0.9234441484441485
📊 Confusion Matrix:
 [[190  25]
 [ 53 216]]



🔍 Target: Type_of_Respiratory_Allergy_IGE_Dander_Animals | Model: RandomForest
📈 Accuracy: 0.8036
🎯 F1 (0): 0.8104 | F1 (1): 0.7934
📊 Precision: 0.8118 | AUC: 0.9039518090605047
📊 Confusion Matrix:
 [[257   0]
 [  0 227]]



🔍 Target: Type_of_Respiratory_Allergy_IGE_Dander_Animals | Model: XGBoost
📈 Accuracy: 0.8017
🎯 F1 (0): 0.8057 | F1 (1): 0.7955
📊 Precision: 0.8094 | AUC: 0.878834296138644
📊 Confusion Matrix:
 [[257   0]
 [  0 227]]



🔍 Target: Type_of_Respiratory_Allergy_IGE_Dander_Animals | Model: LogisticRegression
📈 Accuracy: 0.7398
🎯 F1 (0): 0.7570 | F1 (1): 0.7158
📊 Precision: 0.7476 | AUC: 0.8355004560656735
📊 Confusion Matrix:
 [[220  37]
 [ 47 180]]



🔍 Target: Type_of_Respiratory_Allergy_IGE_Dander_Animals | Model: SVM
📈 Accuracy: 0.7744
🎯 F1 (0): 0.7770 | F1 (1): 0.7702
📊 Precision: 0.7799 | AUC: 0.8453101246579507
📊 Confusion Matrix:
 [[203  54]
 [ 49 178]]



🔍 Target: Type_of_Respiratory_Allergy_IGE_Mite_Cockroach | Model: RandomForest
📈 Accuracy: 0.8760
🎯 F1 (0): 0.8370 | F1 (1): 0.8996
📊 Precision: 0.8802 | AUC: 0.9281715063520872
📊 Confusion Matrix:
 [[194   0]
 [  0 290]]



🔍 Target: Type_of_Respiratory_Allergy_IGE_Mite_Cockroach | Model: XGBoost
📈 Accuracy: 0.8821
🎯 F1 (0): 0.8513 | F1 (1): 0.9021
📊 Precision: 0.8848 | AUC: 0.9378130671506352
📊 Confusion Matrix:
 [[194   0]
 [  0 290]]



🔍 Target: Type_of_Respiratory_Allergy_IGE_Mite_Cockroach | Model: LogisticRegression
📈 Accuracy: 0.7894
🎯 F1 (0): 0.7520 | F1 (1): 0.8156
📊 Precision: 0.8018 | AUC: 0.8872232304900182
📊 Confusion Matrix:
 [[175  19]
 [ 34 256]]



🔍 Target: Type_of_Respiratory_Allergy_IGE_Mite_Cockroach | Model: SVM
📈 Accuracy: 0.7748
🎯 F1 (0): 0.7525 | F1 (1): 0.7921
📊 Precision: 0.8018 | AUC: 0.9018421052631578
📊 Confusion Matrix:
 [[163  31]
 [ 60 230]]



🔍 Target: Type_of_Respiratory_Allergy_IGE_Molds_Yeast | Model: RandomForest
📈 Accuracy: 0.8988
🎯 F1 (0): 0.9291 | F1 (1): 0.8212
📊 Precision: 0.9126 | AUC: 0.9439036426536427
📊 Confusion Matrix:
 [[359   0]
 [  0 125]]



🔍 Target: Type_of_Respiratory_Allergy_IGE_Molds_Yeast | Model: XGBoost
📈 Accuracy: 0.9069
🎯 F1 (0): 0.9357 | F1 (1): 0.8292
📊 Precision: 0.9155 | AUC: 0.9536614774114774
📊 Confusion Matrix:
 [[359   0]
 [  0 125]]



🔍 Target: Type_of_Respiratory_Allergy_IGE_Molds_Yeast | Model: LogisticRegression
📈 Accuracy: 0.7687
🎯 F1 (0): 0.8510 | F1 (1): 0.4754
📊 Precision: 0.7497 | AUC: 0.7446108058608059
📊 Confusion Matrix:
 [[344  15]
 [ 72  53]]



🔍 Target: Type_of_Respiratory_Allergy_IGE_Molds_Yeast | Model: SVM
📈 Accuracy: 0.7789
🎯 F1 (0): 0.8497 | F1 (1): 0.5760
📊 Precision: 0.7857 | AUC: 0.8482244607244608
📊 Confusion Matrix:
 [[348  11]
 [ 70  55]]



🔍 Target: Type_of_Respiratory_Allergy_ARIA | Model: RandomForest
📈 Accuracy: 0.9876
🎯 F1 (0): 0.9818 | F1 (1): 0.9906
📊 Precision: 0.9881 | AUC: 0.9999080882352942
📊 Confusion Matrix:
 [[173   0]
 [  0 311]]



🔍 Target: Type_of_Respiratory_Allergy_ARIA | Model: XGBoost
📈 Accuracy: 0.9938
🎯 F1 (0): 0.9912 | F1 (1): 0.9952
📊 Precision: 0.9941 | AUC: 0.9992528462998103
📊 Confusion Matrix:
 [[173   0]
 [  0 311]]



🔍 Target: Type_of_Respiratory_Allergy_ARIA | Model: LogisticRegression
📈 Accuracy: 0.9917
🎯 F1 (0): 0.9879 | F1 (1): 0.9937
📊 Precision: 0.9920 | AUC: 1.0
📊 Confusion Matrix:
 [[172   1]
 [  0 311]]



🔍 Target: Type_of_Respiratory_Allergy_ARIA | Model: SVM
📈 Accuracy: 0.5849
🎯 F1 (0): 0.5642 | F1 (1): 0.5995
📊 Precision: 0.6678 | AUC: 0.6895543432426734
📊 Confusion Matrix:
 [[  6 167]
 [  1 310]]



🔍 Target: Type_of_Respiratory_Allergy_CONJ | Model: RandomForest
📈 Accuracy: 0.9855
🎯 F1 (0): 0.9893 | F1 (1): 0.9773
📊 Precision: 0.9869 | AUC: 0.9995959595959596
📊 Confusion Matrix:
 [[331   0]
 [  0 153]]



🔍 Target: Type_of_Respiratory_Allergy_CONJ | Model: XGBoost
📈 Accuracy: 0.9979
🎯 F1 (0): 0.9985 | F1 (1): 0.9968
📊 Precision: 0.9980 | AUC: 1.0
📊 Confusion Matrix:
 [[331   0]
 [  0 153]]



🔍 Target: Type_of_Respiratory_Allergy_CONJ | Model: LogisticRegression
📈 Accuracy: 0.9197
🎯 F1 (0): 0.9409 | F1 (1): 0.8733
📊 Precision: 0.9254 | AUC: 0.9455592691622103
📊 Confusion Matrix:
 [[322   9]
 [ 15 138]]



🔍 Target: Type_of_Respiratory_Allergy_CONJ | Model: SVM
📈 Accuracy: 0.6617
🎯 F1 (0): 0.7594 | F1 (1): 0.4178
📊 Precision: 0.6517 | AUC: 0.66525623885918
📊 Confusion Matrix:
 [[319  12]
 [117  36]]



🔍 Target: Type_of_Respiratory_Allergy_IGE_Pollen_Gram | Model: RandomForest
📈 Accuracy: 0.8369
🎯 F1 (0): 0.8124 | F1 (1): 0.8548
📊 Precision: 0.8408 | AUC: 0.9220272682229205
📊 Confusion Matrix:
 [[221   0]
 [  0 263]]



🔍 Target: Type_of_Respiratory_Allergy_IGE_Pollen_Gram | Model: XGBoost
📈 Accuracy: 0.8596
🎯 F1 (0): 0.8416 | F1 (1): 0.8733
📊 Precision: 0.8629 | AUC: 0.947283030978683
📊 Confusion Matrix:
 [[221   0]
 [  0 263]]



🔍 Target: Type_of_Respiratory_Allergy_IGE_Pollen_Gram | Model: LogisticRegression
📈 Accuracy: 0.7810
🎯 F1 (0): 0.7812 | F1 (1): 0.7796
📊 Precision: 0.7923 | AUC: 0.8849884012927491
📊 Confusion Matrix:
 [[203  18]
 [ 42 221]]



🔍 Target: Type_of_Respiratory_Allergy_IGE_Pollen_Gram | Model: SVM
📈 Accuracy: 0.7851
🎯 F1 (0): 0.7752 | F1 (1): 0.7935
📊 Precision: 0.7903 | AUC: 0.8702999898652072
📊 Confusion Matrix:
 [[179  42]
 [ 54 209]]



🔍 Target: Type_of_Respiratory_Allergy_GINA | Model: RandomForest
📈 Accuracy: 0.9835
🎯 F1 (0): 0.9752 | F1 (1): 0.9877
📊 Precision: 0.9843 | AUC: 0.9958139379743833
📊 Confusion Matrix:
 [[167   0]
 [  0 317]]



🔍 Target: Type_of_Respiratory_Allergy_GINA | Model: XGBoost
📈 Accuracy: 0.9814
🎯 F1 (0): 0.9727 | F1 (1): 0.9859
📊 Precision: 0.9821 | AUC: 0.9966029708254268
📊 Confusion Matrix:
 [[167   0]
 [  0 317]]



🔍 Target: Type_of_Respiratory_Allergy_GINA | Model: LogisticRegression
📈 Accuracy: 0.9814
🎯 F1 (0): 0.9727 | F1 (1): 0.9858
📊 Precision: 0.9820 | AUC: 0.9984942036290322
📊 Confusion Matrix:
 [[164   3]
 [  0 317]]



🔍 Target: Type_of_Respiratory_Allergy_GINA | Model: SVM
📈 Accuracy: 0.6800
🎯 F1 (0): 0.4841 | F1 (1): 0.7677
📊 Precision: 0.6685 | AUC: 0.7011003468927894
📊 Confusion Matrix:
 [[ 27 140]
 [  5 312]]


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.metrics import (
    f1_score, accuracy_score, recall_score,
    precision_score, confusion_matrix, roc_auc_score, roc_curve
)
from imblearn.over_sampling import SMOTE
import plotly.graph_objects as go

V2_food = V2[V2["Food_Allergy"] == 1]
targets = ["Type_of_Food_Allergy_Aromatics",
    "Type_of_Food_Allergy_Cereals_&_Seeds",
    "Type_of_Food_Allergy_Egg",
    "Type_of_Food_Allergy_Fish",
    "Type_of_Food_Allergy_Fruits_and_Vegetables",
    "Type_of_Food_Allergy_Mammalian_Milk",
    "Type_of_Food_Allergy_Oral_Syndrom",
    "Type_of_Food_Allergy_Other_Legumes",
    "Type_of_Food_Allergy_Peanut",
    "Type_of_Food_Allergy_Shellfish",
    "Type_of_Food_Allergy_TPO",
    "Type_of_Food_Allergy_Tree_Nuts"]

models = {
    "RandomForest": RandomForestClassifier(random_state=42),
    "XGBoost": XGBClassifier(random_state=42, eval_metric="logloss", use_label_encoder=False),
    "LogisticRegression": LogisticRegression(max_iter=1000, random_state=42),
    "SVM": SVC(probability=True, random_state=42)
}

X=V2_food.copy()
X.drop(target_1, axis=1, inplace=True)
X.drop(extra_columns, axis=1, inplace=True)
X.drop(extra, axis=1, inplace=True)
X.drop(inconnu, axis=1, inplace=True)
X = X.iloc[:, 1:]
results_food = []

kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

for target in targets:
    y = V2_food[target]

    for model_name, base_model in models.items():
        f1_class0_scores, f1_class1_scores = [], []
        precision_scores, acc_scores, recall_scores, auc_scores = [], [], [], []

        for train_idx, test_idx in kfold.split(X, y):
            X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
            y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

            smote = SMOTE(random_state=42)
            X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

            base_model.fit(X_train_res, y_train_res)
            y_pred = base_model.predict(X_test)

            acc_scores.append(accuracy_score(y_test, y_pred))
            recall_scores.append(recall_score(y_test, y_pred, zero_division=0))
            precision_scores.append(precision_score(y_test, y_pred, average='weighted', zero_division=0))
            f1_class0_scores.append(f1_score(y_test, y_pred, pos_label=0, zero_division=0))
            f1_class1_scores.append(f1_score(y_test, y_pred, pos_label=1, zero_division=0))

            if hasattr(base_model, "predict_proba"):
                y_proba = base_model.predict_proba(X_test)[:, 1]
                auc_scores.append(roc_auc_score(y_test, y_proba))

        base_model.fit(X, y)
        y_pred_full = base_model.predict(X)
        y_proba_full = base_model.predict_proba(X)[:, 1] if hasattr(base_model, "predict_proba") else None
        matrix = confusion_matrix(y, y_pred_full)

        print(f"\n🔍 Target: {target} | Model: {model_name}")
        print(f"📈 Accuracy: {np.mean(acc_scores):.4f}")
        print(f"🎯 F1 (0): {np.mean(f1_class0_scores):.4f} | F1 (1): {np.mean(f1_class1_scores):.4f}")
        print(f"📊 Precision: {np.mean(precision_scores):.4f} | AUC: {np.mean(auc_scores) if auc_scores else 'N/A'}")
        print("📊 Confusion Matrix:\n", matrix)

        if y_proba_full is not None:
            fpr, tpr, _ = roc_curve(y, y_proba_full)
            fig = go.Figure()
            fig.add_trace(go.Scatter(x=fpr, y=tpr, mode='lines', name=f"{model_name} (AUC={np.mean(auc_scores):.2f})"))
            fig.add_trace(go.Scatter(x=[0, 1], y=[0, 1], mode='lines', name='Random', line=dict(dash='dash')))
            fig.update_layout(
                title=f"ROC Curve - {target} - {model_name}",
                xaxis_title="False Positive Rate",
                yaxis_title="True Positive Rate",
                width=700, height=500
            )
            fig.show()

        results_food.append({
            "Target": target,
            "Model": model_name,
            "F1_Class_0": np.mean(f1_class0_scores),
            "F1_Class_1": np.mean(f1_class1_scores),
            "Precision": np.mean(precision_scores),
            "Accuracy": np.mean(acc_scores),
            "Recall": np.mean(recall_scores),
            "AUC_ROC": np.mean(auc_scores) if auc_scores else np.nan
        })

pd.DataFrame(results_food).to_csv("results_V2_food.csv", index=False)


🔍 Target: Type_of_Food_Allergy_Aromatics | Model: RandomForest
📈 Accuracy: 0.9776
🎯 F1 (0): 0.9887 | F1 (1): 0.0667
📊 Precision: 0.9662 | AUC: 0.8009273772204806
📊 Confusion Matrix:
 [[878   0]
 [  0  16]]



🔍 Target: Type_of_Food_Allergy_Aromatics | Model: XGBoost
📈 Accuracy: 0.9754
🎯 F1 (0): 0.9875 | F1 (1): 0.1900
📊 Precision: 0.9727 | AUC: 0.7526907001044931
📊 Confusion Matrix:
 [[878   0]
 [  0  16]]



🔍 Target: Type_of_Food_Allergy_Aromatics | Model: LogisticRegression
📈 Accuracy: 0.9351
🎯 F1 (0): 0.9662 | F1 (1): 0.0832
📊 Precision: 0.9684 | AUC: 0.7120885579937305
📊 Confusion Matrix:
 [[878   0]
 [ 15   1]]



🔍 Target: Type_of_Food_Allergy_Aromatics | Model: SVM
📈 Accuracy: 0.7998
🎯 F1 (0): 0.8872 | F1 (1): 0.0868
📊 Precision: 0.9737 | AUC: 0.7221068443051202
📊 Confusion Matrix:
 [[878   0]
 [ 16   0]]



🔍 Target: Type_of_Food_Allergy_Cereals_&_Seeds | Model: RandomForest
📈 Accuracy: 0.9608
🎯 F1 (0): 0.9800 | F1 (1): 0.0000
📊 Precision: 0.9403 | AUC: 0.7197986278178738
📊 Confusion Matrix:
 [[867   0]
 [  0  27]]



🔍 Target: Type_of_Food_Allergy_Cereals_&_Seeds | Model: XGBoost
📈 Accuracy: 0.9507
🎯 F1 (0): 0.9747 | F1 (1): 0.0000
📊 Precision: 0.9400 | AUC: 0.6871380201372181
📊 Confusion Matrix:
 [[867   0]
 [  0  27]]



🔍 Target: Type_of_Food_Allergy_Cereals_&_Seeds | Model: LogisticRegression
📈 Accuracy: 0.9038
🎯 F1 (0): 0.9491 | F1 (1): 0.0832
📊 Precision: 0.9447 | AUC: 0.5341441682259646
📊 Confusion Matrix:
 [[867   0]
 [ 27   0]]



🔍 Target: Type_of_Food_Allergy_Cereals_&_Seeds | Model: SVM
📈 Accuracy: 0.7605
🎯 F1 (0): 0.8612 | F1 (1): 0.1009
📊 Precision: 0.9522 | AUC: 0.5535685645549318
📊 Confusion Matrix:
 [[867   0]
 [ 27   0]]



🔍 Target: Type_of_Food_Allergy_Egg | Model: RandomForest
📈 Accuracy: 0.9844
🎯 F1 (0): 0.9921 | F1 (1): 0.0667
📊 Precision: 0.9707 | AUC: 0.9022727272727271
📊 Confusion Matrix:
 [[880   0]
 [  0  14]]



🔍 Target: Type_of_Food_Allergy_Egg | Model: XGBoost
📈 Accuracy: 0.9833
🎯 F1 (0): 0.9915 | F1 (1): 0.3500
📊 Precision: 0.9800 | AUC: 0.9335227272727273
📊 Confusion Matrix:
 [[880   0]
 [  0  14]]



🔍 Target: Type_of_Food_Allergy_Egg | Model: LogisticRegression
📈 Accuracy: 0.9519
🎯 F1 (0): 0.9752 | F1 (1): 0.0933
📊 Precision: 0.9726 | AUC: 0.7772727272727273
📊 Confusion Matrix:
 [[880   0]
 [ 12   2]]



🔍 Target: Type_of_Food_Allergy_Egg | Model: SVM
📈 Accuracy: 0.8222
🎯 F1 (0): 0.9013 | F1 (1): 0.0520
📊 Precision: 0.9716 | AUC: 0.6448863636363636
📊 Confusion Matrix:
 [[880   0]
 [ 14   0]]



🔍 Target: Type_of_Food_Allergy_Fish | Model: RandomForest
📈 Accuracy: 0.9731
🎯 F1 (0): 0.9864 | F1 (1): 0.0000
📊 Precision: 0.9557 | AUC: 0.6779127481713689
📊 Confusion Matrix:
 [[874   0]
 [  0  20]]



🔍 Target: Type_of_Food_Allergy_Fish | Model: XGBoost
📈 Accuracy: 0.9698
🎯 F1 (0): 0.9846 | F1 (1): 0.0667
📊 Precision: 0.9589 | AUC: 0.6398968129571577
📊 Confusion Matrix:
 [[874   0]
 [  0  20]]



🔍 Target: Type_of_Food_Allergy_Fish | Model: LogisticRegression
📈 Accuracy: 0.9239
🎯 F1 (0): 0.9601 | F1 (1): 0.0667
📊 Precision: 0.9589 | AUC: 0.550208986415883
📊 Confusion Matrix:
 [[874   0]
 [ 20   0]]



🔍 Target: Type_of_Food_Allergy_Fish | Model: SVM
📈 Accuracy: 0.7616
🎯 F1 (0): 0.8624 | F1 (1): 0.0838
📊 Precision: 0.9626 | AUC: 0.6703565830721003
📊 Confusion Matrix:
 [[874   0]
 [ 20   0]]



🔍 Target: Type_of_Food_Allergy_Fruits_and_Vegetables | Model: RandomForest
📈 Accuracy: 0.9508
🎯 F1 (0): 0.9747 | F1 (1): 0.0733
📊 Precision: 0.9278 | AUC: 0.8438275193798448
📊 Confusion Matrix:
 [[859   0]
 [  0  35]]



🔍 Target: Type_of_Food_Allergy_Fruits_and_Vegetables | Model: XGBoost
📈 Accuracy: 0.9530
🎯 F1 (0): 0.9757 | F1 (1): 0.2305
📊 Precision: 0.9409 | AUC: 0.8612870497036024
📊 Confusion Matrix:
 [[859   0]
 [  0  35]]



🔍 Target: Type_of_Food_Allergy_Fruits_and_Vegetables | Model: LogisticRegression
📈 Accuracy: 0.9162
🎯 F1 (0): 0.9554 | F1 (1): 0.2003
📊 Precision: 0.9395 | AUC: 0.7425227998176015
📊 Confusion Matrix:
 [[858   1]
 [ 28   7]]



🔍 Target: Type_of_Food_Allergy_Fruits_and_Vegetables | Model: SVM
📈 Accuracy: 0.8344
🎯 F1 (0): 0.9069 | F1 (1): 0.2224
📊 Precision: 0.9499 | AUC: 0.8020816233470134
📊 Confusion Matrix:
 [[859   0]
 [ 35   0]]



🔍 Target: Type_of_Food_Allergy_Mammalian_Milk | Model: RandomForest
📈 Accuracy: 0.9899
🎯 F1 (0): 0.9949 | F1 (1): 0.0000
📊 Precision: 0.9800 | AUC: nan
📊 Confusion Matrix:
 [[885   0]
 [  0   9]]



🔍 Target: Type_of_Food_Allergy_Mammalian_Milk | Model: XGBoost
📈 Accuracy: 0.9855
🎯 F1 (0): 0.9927 | F1 (1): 0.0000
📊 Precision: 0.9799 | AUC: nan
📊 Confusion Matrix:
 [[885   0]
 [  0   9]]



🔍 Target: Type_of_Food_Allergy_Mammalian_Milk | Model: LogisticRegression
📈 Accuracy: 0.9697
🎯 F1 (0): 0.9846 | F1 (1): 0.0000
📊 Precision: 0.9798 | AUC: nan
📊 Confusion Matrix:
 [[885   0]
 [  9   0]]



🔍 Target: Type_of_Food_Allergy_Mammalian_Milk | Model: SVM
📈 Accuracy: 0.8232
🎯 F1 (0): 0.9022 | F1 (1): 0.0000
📊 Precision: 0.9780 | AUC: nan
📊 Confusion Matrix:
 [[885   0]
 [  9   0]]



🔍 Target: Type_of_Food_Allergy_Oral_Syndrom | Model: RandomForest
📈 Accuracy: 0.9732
🎯 F1 (0): 0.9849 | F1 (1): 0.8815
📊 Precision: 0.9742 | AUC: 0.9989073426573427
📊 Confusion Matrix:
 [[777   0]
 [  0 117]]



🔍 Target: Type_of_Food_Allergy_Oral_Syndrom | Model: XGBoost
📈 Accuracy: 0.9989
🎯 F1 (0): 0.9994 | F1 (1): 0.9960
📊 Precision: 0.9990 | AUC: 0.999465811965812
📊 Confusion Matrix:
 [[777   0]
 [  0 117]]



🔍 Target: Type_of_Food_Allergy_Oral_Syndrom | Model: LogisticRegression
📈 Accuracy: 0.8379
🎯 F1 (0): 0.9058 | F1 (1): 0.4118
📊 Precision: 0.8469 | AUC: 0.8055735930735931
📊 Confusion Matrix:
 [[764  13]
 [ 77  40]]



🔍 Target: Type_of_Food_Allergy_Oral_Syndrom | Model: SVM
📈 Accuracy: 0.6700
🎯 F1 (0): 0.7741 | F1 (1): 0.3789
📊 Precision: 0.8590 | AUC: 0.7192404817404817
📊 Confusion Matrix:
 [[777   0]
 [116   1]]



🔍 Target: Type_of_Food_Allergy_Other_Legumes | Model: RandomForest
📈 Accuracy: 0.9799
🎯 F1 (0): 0.9898 | F1 (1): 0.0000
📊 Precision: 0.9646 | AUC: 0.7299536311389759
📊 Confusion Matrix:
 [[878   0]
 [  0  16]]



🔍 Target: Type_of_Food_Allergy_Other_Legumes | Model: XGBoost
📈 Accuracy: 0.9788
🎯 F1 (0): 0.9892 | F1 (1): 0.0667
📊 Precision: 0.9662 | AUC: 0.6641588296760711
📊 Confusion Matrix:
 [[878   0]
 [  0  16]]



🔍 Target: Type_of_Food_Allergy_Other_Legumes | Model: LogisticRegression
📈 Accuracy: 0.9474
🎯 F1 (0): 0.9728 | F1 (1): 0.0686
📊 Precision: 0.9667 | AUC: 0.5197165621734587
📊 Confusion Matrix:
 [[878   0]
 [ 16   0]]



🔍 Target: Type_of_Food_Allergy_Other_Legumes | Model: SVM
📈 Accuracy: 0.7806
🎯 F1 (0): 0.8747 | F1 (1): 0.0473
📊 Precision: 0.9677 | AUC: 0.5754049111807733
📊 Confusion Matrix:
 [[878   0]
 [ 16   0]]



🔍 Target: Type_of_Food_Allergy_Peanut | Model: RandomForest
📈 Accuracy: 0.9127
🎯 F1 (0): 0.9536 | F1 (1): 0.2453
📊 Precision: 0.8940 | AUC: 0.8190126359094917
📊 Confusion Matrix:
 [[826   0]
 [  0  68]]



🔍 Target: Type_of_Food_Allergy_Peanut | Model: XGBoost
📈 Accuracy: 0.9072
🎯 F1 (0): 0.9502 | F1 (1): 0.3065
📊 Precision: 0.8972 | AUC: 0.8572869876719421
📊 Confusion Matrix:
 [[826   0]
 [  0  68]]



🔍 Target: Type_of_Food_Allergy_Peanut | Model: LogisticRegression
📈 Accuracy: 0.8657
🎯 F1 (0): 0.9260 | F1 (1): 0.2537
📊 Precision: 0.8876 | AUC: 0.6785497390257895
📊 Confusion Matrix:
 [[821   5]
 [ 55  13]]



🔍 Target: Type_of_Food_Allergy_Peanut | Model: SVM
📈 Accuracy: 0.7369
🎯 F1 (0): 0.8377 | F1 (1): 0.2782
📊 Precision: 0.9020 | AUC: 0.7270146789247581
📊 Confusion Matrix:
 [[826   0]
 [ 68   0]]



🔍 Target: Type_of_Food_Allergy_Shellfish | Model: RandomForest
📈 Accuracy: 0.9698
🎯 F1 (0): 0.9847 | F1 (1): 0.0500
📊 Precision: 0.9450 | AUC: 0.7830905283792213
📊 Confusion Matrix:
 [[867   0]
 [  0  27]]



🔍 Target: Type_of_Food_Allergy_Shellfish | Model: XGBoost
📈 Accuracy: 0.9609
🎯 F1 (0): 0.9799 | F1 (1): 0.2000
📊 Precision: 0.9547 | AUC: 0.8007885592087678
📊 Confusion Matrix:
 [[867   0]
 [  0  27]]



🔍 Target: Type_of_Food_Allergy_Shellfish | Model: LogisticRegression
📈 Accuracy: 0.9250
🎯 F1 (0): 0.9606 | F1 (1): 0.1430
📊 Precision: 0.9500 | AUC: 0.7110665597433841
📊 Confusion Matrix:
 [[867   0]
 [ 27   0]]



🔍 Target: Type_of_Food_Allergy_Shellfish | Model: SVM
📈 Accuracy: 0.7638
🎯 F1 (0): 0.8619 | F1 (1): 0.1352
📊 Precision: 0.9566 | AUC: 0.7325180433039294
📊 Confusion Matrix:
 [[867   0]
 [ 27   0]]



🔍 Target: Type_of_Food_Allergy_TPO | Model: RandomForest
📈 Accuracy: 0.9396
🎯 F1 (0): 0.9685 | F1 (1): 0.2317
📊 Precision: 0.9247 | AUC: 0.8500644257703082
📊 Confusion Matrix:
 [[848   0]
 [  0  46]]



🔍 Target: Type_of_Food_Allergy_TPO | Model: XGBoost
📈 Accuracy: 0.9317
🎯 F1 (0): 0.9641 | F1 (1): 0.2683
📊 Precision: 0.9277 | AUC: 0.8226974789915967
📊 Confusion Matrix:
 [[848   0]
 [  0  46]]



🔍 Target: Type_of_Food_Allergy_TPO | Model: LogisticRegression
📈 Accuracy: 0.9127
🎯 F1 (0): 0.9536 | F1 (1): 0.2230
📊 Precision: 0.9231 | AUC: 0.7879887955182073
📊 Confusion Matrix:
 [[845   3]
 [ 36  10]]



🔍 Target: Type_of_Food_Allergy_TPO | Model: SVM
📈 Accuracy: 0.8064
🎯 F1 (0): 0.8873 | F1 (1): 0.2910
📊 Precision: 0.9433 | AUC: 0.8249019607843138
📊 Confusion Matrix:
 [[848   0]
 [ 46   0]]



🔍 Target: Type_of_Food_Allergy_Tree_Nuts | Model: RandomForest
📈 Accuracy: 0.9172
🎯 F1 (0): 0.9560 | F1 (1): 0.2820
📊 Precision: 0.8992 | AUC: 0.8458188153310104
📊 Confusion Matrix:
 [[820   0]
 [  0  74]]



🔍 Target: Type_of_Food_Allergy_Tree_Nuts | Model: XGBoost
📈 Accuracy: 0.9183
🎯 F1 (0): 0.9560 | F1 (1): 0.4085
📊 Precision: 0.9070 | AUC: 0.8562282229965158
📊 Confusion Matrix:
 [[820   0]
 [  0  74]]



🔍 Target: Type_of_Food_Allergy_Tree_Nuts | Model: LogisticRegression
📈 Accuracy: 0.8681
🎯 F1 (0): 0.9271 | F1 (1): 0.2944
📊 Precision: 0.8830 | AUC: 0.7658101045296167
📊 Confusion Matrix:
 [[813   7]
 [ 60  14]]



🔍 Target: Type_of_Food_Allergy_Tree_Nuts | Model: SVM
📈 Accuracy: 0.7002
🎯 F1 (0): 0.8106 | F1 (1): 0.2641
📊 Precision: 0.8922 | AUC: 0.7194033101045296
📊 Confusion Matrix:
 [[820   0]
 [ 74   0]]


#Ne lancer pas cette partie, c pour la recherche des hyperparametres

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedKFold, GridSearchCV
from xgboost import XGBClassifier

# Grille des hyperparamètres à tester
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.1, 0.2],
    'subsample': [0.8, 1],
    'colsample_bytree': [0.8, 1],
    'gamma': [0, 1, 5]
}

# Données et targets
X = V1.copy()
X.drop(target_1, axis=1, inplace=True)
X.drop(extra_columns, axis=1, inplace=True)
X.drop(extra, axis=1, inplace=True)
X = X.iloc[:, 1:]

targets = [
    "Allergy_Present",
    "Respiratory_Allergy",
    "Food_Allergy",
    "Venom_Allergy",
    "Severe_Allergy",
    "Type_of_Food_Allergy_Other",
    "Type_of_Respiratory_Allergy_IGE_Pollen_Herb",
    "Type_of_Respiratory_Allergy_IGE_Pollen_Tree",
    "Type_of_Respiratory_Allergy_IGE_Dander_Animals",
    "Type_of_Respiratory_Allergy_IGE_Mite_Cockroach",
    "Type_of_Respiratory_Allergy_IGE_Molds_Yeast",
    "Type_of_Respiratory_Allergy_ARIA",
    "Type_of_Respiratory_Allergy_CONJ",
    "Type_of_Respiratory_Allergy_IGE_Pollen_Gram",
    "Type_of_Respiratory_Allergy_GINA",
    "Type_of_Food_Allergy_Aromatics",
    "Type_of_Food_Allergy_Cereals_&_Seeds",
    "Type_of_Food_Allergy_Egg",
    "Type_of_Food_Allergy_Fish",
    "Type_of_Food_Allergy_Fruits_and_Vegetables",
    "Type_of_Food_Allergy_Mammalian_Milk",
    "Type_of_Food_Allergy_Oral_Syndrom",
    "Type_of_Food_Allergy_Other_Legumes",
    "Type_of_Food_Allergy_Peanut",
    "Type_of_Food_Allergy_Shellfish",
    "Type_of_Food_Allergy_TPO",
    "Type_of_Food_Allergy_Tree_Nuts",
    "Type_of_Venom_Allergy_ATCD_Venom",
    "Type_of_Venom_Allergy_IGE_Venom",
]

all_results = []

for target in targets:
    print(f"\n🔍 Recherche d'hyperparamètres pour le target: {target}")

    y = V1[target]
    filtered_X = X.copy()
    filtered_y = y.copy()

    if target in ["Severe_Allergy", "Respiratory_Allergy", "Food_Allergy", "Venom_Allergy"]:
        mask = V1["Allergy_Present"] == 1
        filtered_X = filtered_X[mask]
        filtered_y = filtered_y[mask]
    elif target.startswith("Type_of_Respiratory_Allergy_"):
        mask = V1["Respiratory_Allergy"] == 1
        filtered_X = filtered_X[mask]
        filtered_y = filtered_y[mask]
    elif target.startswith("Type_of_Food_Allergy_"):
        mask = V1["Food_Allergy"] == 1
        filtered_X = filtered_X[mask]
        filtered_y = filtered_y[mask]

    if len(filtered_y.unique()) < 2 or len(filtered_y) < 10:
        print(f" Pas assez de données pour {target}, on passe.")
        continue

    model = XGBClassifier(random_state=42, eval_metric="logloss", use_label_encoder=False)

    grid_search = GridSearchCV(
        estimator=model,
        param_grid=param_grid,
        scoring='f1',
        cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=42),
        n_jobs=-1,
        verbose=1
    )

    grid_search.fit(filtered_X, filtered_y)


    best_params = grid_search.best_params_
    best_score = grid_search.best_score_

    best_params['Target'] = target
    best_params['Best_F1_Score'] = best_score

    all_results.append(best_params)

df_results = pd.DataFrame(all_results)
df_results = df_results[['Target'] + [col for col in df_results.columns if col != 'Target']]  # Remettre Target en premier
df_results.to_csv("xgboost_best_hyperparameters_V1.csv", index=False)


🔍 Recherche d'hyperparamètres pour le target: Allergy_Present
Fitting 5 folds for each of 324 candidates, totalling 1620 fits

🔍 Recherche d'hyperparamètres pour le target: Respiratory_Allergy
Fitting 5 folds for each of 324 candidates, totalling 1620 fits

🔍 Recherche d'hyperparamètres pour le target: Food_Allergy
Fitting 5 folds for each of 324 candidates, totalling 1620 fits

🔍 Recherche d'hyperparamètres pour le target: Venom_Allergy
Fitting 5 folds for each of 324 candidates, totalling 1620 fits

🔍 Recherche d'hyperparamètres pour le target: Severe_Allergy
Fitting 5 folds for each of 324 candidates, totalling 1620 fits

🔍 Recherche d'hyperparamètres pour le target: Type_of_Food_Allergy_Other
Fitting 5 folds for each of 324 candidates, totalling 1620 fits

🔍 Recherche d'hyperparamètres pour le target: Type_of_Respiratory_Allergy_IGE_Pollen_Herb
Fitting 5 folds for each of 324 candidates, totalling 1620 fits

🔍 Recherche d'hyperparamètres pour le target: Type_of_Respiratory_Allergy

#TOP Features

In [ ]:
import pandas as pd
import numpy as np
from xgboost import XGBClassifier
import plotly.graph_objects as go

targets = [
    "Allergy_Present", "Respiratory_Allergy", "Food_Allergy", "Venom_Allergy",
    "Severe_Allergy", "Type_of_Food_Allergy_Other", "Type_of_Respiratory_Allergy_IGE_Pollen_Herb",
    "Type_of_Respiratory_Allergy_IGE_Pollen_Tree", "Type_of_Respiratory_Allergy_IGE_Dander_Animals",
    "Type_of_Respiratory_Allergy_IGE_Mite_Cockroach", "Type_of_Respiratory_Allergy_IGE_Molds_Yeast",
    "Type_of_Respiratory_Allergy_ARIA", "Type_of_Respiratory_Allergy_CONJ",
    "Type_of_Respiratory_Allergy_IGE_Pollen_Gram", "Type_of_Respiratory_Allergy_GINA",
    "Type_of_Food_Allergy_Aromatics", "Type_of_Food_Allergy_Cereals_&_Seeds",
    "Type_of_Food_Allergy_Egg", "Type_of_Food_Allergy_Fish", "Type_of_Food_Allergy_Fruits_and_Vegetables",
    "Type_of_Food_Allergy_Mammalian_Milk", "Type_of_Food_Allergy_Oral_Syndrom",
    "Type_of_Food_Allergy_Other_Legumes", "Type_of_Food_Allergy_Peanut",
    "Type_of_Food_Allergy_Shellfish", "Type_of_Food_Allergy_TPO", "Type_of_Food_Allergy_Tree_Nuts",
    "Type_of_Venom_Allergy_ATCD_Venom", "Type_of_Venom_Allergy_IGE_Venom"
]

inconnu = ["Treatment_of_athsma_9", "Treatment_of_rhinitis_9", "General_cofactors_9",
           "Age_of_onsets_9", "ARIA_(rhinitis)_9", "GINA_(asthma)_9", "Treatment_of_atopic_dematitis_9"]

X = V2.copy()
X.drop(target_1, axis=1, inplace=True)
X.drop(extra_columns, axis=1, inplace=True)
X.drop(extra, axis=1, inplace=True)
X.drop(inconnu, axis=1, inplace=True)
X = X.iloc[:, 1:]

def plot_top_features(model, X_sub, y_sub, target):
    if len(np.unique(y_sub)) < 2:
        print(f"⚠️ Target '{target}' contient une seule classe ({np.unique(y_sub)}). Skip.")
        return

    model.fit(X_sub, y_sub)
    importances = model.feature_importances_
    top_indices = np.argsort(importances)[::-1][:10]
    features = X_sub.columns[top_indices]
    scores = importances[top_indices]

    fig = go.Figure(go.Bar(
        x=scores[::-1],
        y=features[::-1],
        orientation='h',
        text=[f"{s:.3f}" for s in scores[::-1]],
        textposition='outside'
    ))
    fig.update_layout(
        title=f"Top 10 Features pour la cible '{target}' (XGBoost)",
        xaxis_title="Importance",
        yaxis_title="Feature",
        width=800, height=500
    )
    fig.show()

for target in targets:
    X_sub = X.copy()
    y_sub = V2[target]
    model = XGBClassifier(random_state=42, eval_metric="logloss", use_label_encoder=False)
    plot_top_features(model, X_sub, y_sub, target)

⚠️ Target 'Type_of_Food_Allergy_Oral_Syndrom' contient une seule classe ([0]). Skip.


⚠️ Target 'Type_of_Venom_Allergy_IGE_Venom' contient une seule classe ([0]). Skip.
